name: Build and Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# required to allow push to gh-pages using github_token
permissions:
  contents: write

jobs:
  docs-build:
    name: "Build Docs"
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # python ----
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install the project
        run: uv sync --group docs && uv pip install .[]

      # quarto ----
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Build docs
        run: |
          cd docs && uv run quartodoc build --verbose && uv run quarto render

      # save ----
      - name: Save docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_site

      # publish to gh-pages ----
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          publish_branch: gh-pages
          force_orphan: true
