name: CI Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    # concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
      fail-fast: false
    permissions:
      pull-requests: write
      actions: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # python ----
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Sync dependencies
        run: uv sync --locked --extra test

      - name: Install project editable
        run: uv pip install -e ".[test]"

      # pytest
      - name: Test
        run: |
          uv run pytest --cov --cov-branch --cov-report=xml

      # codedev
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
